/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-03 at 22:05:18 UTC 
 * Modify at your own risk.
 */

package com.appspot.rvaserver2.core.model;

/**
 * Model definition for CompanyWrapper.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Rise Core API (experimental). For a detailed
 * explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CompanyWrapper extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean adsEarn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean adsInterested;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String alertKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AlertSettingsWrapper alertSettings;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String authKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime changeDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String changedBy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String city;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String claimId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer companyStatus;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime companyStatusChangeDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String companyType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime creationDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fax;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean mailSyncEnabled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> marketSegments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> notificationEmails;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String parentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private JsonMap parentSettings;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String postalCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String province;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sellerId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> servicesProvided;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private JsonMap settings;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String street;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> targetGroups;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telephone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer timeZoneOffset;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String unit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String viewsPerDisplay;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAdsEarn() {
    return adsEarn;
  }

  /**
   * @param adsEarn adsEarn or {@code null} for none
   */
  public CompanyWrapper setAdsEarn(java.lang.Boolean adsEarn) {
    this.adsEarn = adsEarn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAdsInterested() {
    return adsInterested;
  }

  /**
   * @param adsInterested adsInterested or {@code null} for none
   */
  public CompanyWrapper setAdsInterested(java.lang.Boolean adsInterested) {
    this.adsInterested = adsInterested;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAlertKey() {
    return alertKey;
  }

  /**
   * @param alertKey alertKey or {@code null} for none
   */
  public CompanyWrapper setAlertKey(java.lang.String alertKey) {
    this.alertKey = alertKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public AlertSettingsWrapper getAlertSettings() {
    return alertSettings;
  }

  /**
   * @param alertSettings alertSettings or {@code null} for none
   */
  public CompanyWrapper setAlertSettings(AlertSettingsWrapper alertSettings) {
    this.alertSettings = alertSettings;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthKey() {
    return authKey;
  }

  /**
   * @param authKey authKey or {@code null} for none
   */
  public CompanyWrapper setAuthKey(java.lang.String authKey) {
    this.authKey = authKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getChangeDate() {
    return changeDate;
  }

  /**
   * @param changeDate changeDate or {@code null} for none
   */
  public CompanyWrapper setChangeDate(com.google.api.client.util.DateTime changeDate) {
    this.changeDate = changeDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getChangedBy() {
    return changedBy;
  }

  /**
   * @param changedBy changedBy or {@code null} for none
   */
  public CompanyWrapper setChangedBy(java.lang.String changedBy) {
    this.changedBy = changedBy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCity() {
    return city;
  }

  /**
   * @param city city or {@code null} for none
   */
  public CompanyWrapper setCity(java.lang.String city) {
    this.city = city;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClaimId() {
    return claimId;
  }

  /**
   * @param claimId claimId or {@code null} for none
   */
  public CompanyWrapper setClaimId(java.lang.String claimId) {
    this.claimId = claimId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCompanyStatus() {
    return companyStatus;
  }

  /**
   * @param companyStatus companyStatus or {@code null} for none
   */
  public CompanyWrapper setCompanyStatus(java.lang.Integer companyStatus) {
    this.companyStatus = companyStatus;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCompanyStatusChangeDate() {
    return companyStatusChangeDate;
  }

  /**
   * @param companyStatusChangeDate companyStatusChangeDate or {@code null} for none
   */
  public CompanyWrapper setCompanyStatusChangeDate(com.google.api.client.util.DateTime companyStatusChangeDate) {
    this.companyStatusChangeDate = companyStatusChangeDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompanyType() {
    return companyType;
  }

  /**
   * @param companyType companyType or {@code null} for none
   */
  public CompanyWrapper setCompanyType(java.lang.String companyType) {
    this.companyType = companyType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * @param country country or {@code null} for none
   */
  public CompanyWrapper setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreationDate() {
    return creationDate;
  }

  /**
   * @param creationDate creationDate or {@code null} for none
   */
  public CompanyWrapper setCreationDate(com.google.api.client.util.DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFax() {
    return fax;
  }

  /**
   * @param fax fax or {@code null} for none
   */
  public CompanyWrapper setFax(java.lang.String fax) {
    this.fax = fax;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CompanyWrapper setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public CompanyWrapper setLatitude(java.lang.Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public CompanyWrapper setLongitude(java.lang.Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMailSyncEnabled() {
    return mailSyncEnabled;
  }

  /**
   * @param mailSyncEnabled mailSyncEnabled or {@code null} for none
   */
  public CompanyWrapper setMailSyncEnabled(java.lang.Boolean mailSyncEnabled) {
    this.mailSyncEnabled = mailSyncEnabled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getMarketSegments() {
    return marketSegments;
  }

  /**
   * @param marketSegments marketSegments or {@code null} for none
   */
  public CompanyWrapper setMarketSegments(java.util.List<java.lang.String> marketSegments) {
    this.marketSegments = marketSegments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public CompanyWrapper setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getNotificationEmails() {
    return notificationEmails;
  }

  /**
   * @param notificationEmails notificationEmails or {@code null} for none
   */
  public CompanyWrapper setNotificationEmails(java.util.List<java.lang.String> notificationEmails) {
    this.notificationEmails = notificationEmails;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getParentId() {
    return parentId;
  }

  /**
   * @param parentId parentId or {@code null} for none
   */
  public CompanyWrapper setParentId(java.lang.String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public JsonMap getParentSettings() {
    return parentSettings;
  }

  /**
   * @param parentSettings parentSettings or {@code null} for none
   */
  public CompanyWrapper setParentSettings(JsonMap parentSettings) {
    this.parentSettings = parentSettings;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPostalCode() {
    return postalCode;
  }

  /**
   * @param postalCode postalCode or {@code null} for none
   */
  public CompanyWrapper setPostalCode(java.lang.String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProvince() {
    return province;
  }

  /**
   * @param province province or {@code null} for none
   */
  public CompanyWrapper setProvince(java.lang.String province) {
    this.province = province;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSellerId() {
    return sellerId;
  }

  /**
   * @param sellerId sellerId or {@code null} for none
   */
  public CompanyWrapper setSellerId(java.lang.String sellerId) {
    this.sellerId = sellerId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getServicesProvided() {
    return servicesProvided;
  }

  /**
   * @param servicesProvided servicesProvided or {@code null} for none
   */
  public CompanyWrapper setServicesProvided(java.util.List<java.lang.String> servicesProvided) {
    this.servicesProvided = servicesProvided;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public JsonMap getSettings() {
    return settings;
  }

  /**
   * @param settings settings or {@code null} for none
   */
  public CompanyWrapper setSettings(JsonMap settings) {
    this.settings = settings;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStreet() {
    return street;
  }

  /**
   * @param street street or {@code null} for none
   */
  public CompanyWrapper setStreet(java.lang.String street) {
    this.street = street;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTargetGroups() {
    return targetGroups;
  }

  /**
   * @param targetGroups targetGroups or {@code null} for none
   */
  public CompanyWrapper setTargetGroups(java.util.List<java.lang.String> targetGroups) {
    this.targetGroups = targetGroups;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelephone() {
    return telephone;
  }

  /**
   * @param telephone telephone or {@code null} for none
   */
  public CompanyWrapper setTelephone(java.lang.String telephone) {
    this.telephone = telephone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTimeZoneOffset() {
    return timeZoneOffset;
  }

  /**
   * @param timeZoneOffset timeZoneOffset or {@code null} for none
   */
  public CompanyWrapper setTimeZoneOffset(java.lang.Integer timeZoneOffset) {
    this.timeZoneOffset = timeZoneOffset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnit() {
    return unit;
  }

  /**
   * @param unit unit or {@code null} for none
   */
  public CompanyWrapper setUnit(java.lang.String unit) {
    this.unit = unit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getViewsPerDisplay() {
    return viewsPerDisplay;
  }

  /**
   * @param viewsPerDisplay viewsPerDisplay or {@code null} for none
   */
  public CompanyWrapper setViewsPerDisplay(java.lang.String viewsPerDisplay) {
    this.viewsPerDisplay = viewsPerDisplay;
    return this;
  }

  @Override
  public CompanyWrapper set(String fieldName, Object value) {
    return (CompanyWrapper) super.set(fieldName, value);
  }

  @Override
  public CompanyWrapper clone() {
    return (CompanyWrapper) super.clone();
  }

}
