/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-11-26 at 19:48:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.rvaserver2.core.model;

/**
 * Model definition for DistributionItemWrapper.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Rise Core API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DistributionItemWrapper extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> displayIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String itemId;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getDisplayIds() {
    return displayIds;
  }

  /**
   * @param displayIds displayIds or {@code null} for none
   */
  public DistributionItemWrapper setDisplayIds(java.util.List<java.lang.String> displayIds) {
    this.displayIds = displayIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getItemId() {
    return itemId;
  }

  /**
   * @param itemId itemId or {@code null} for none
   */
  public DistributionItemWrapper setItemId(java.lang.String itemId) {
    this.itemId = itemId;
    return this;
  }

  @Override
  public DistributionItemWrapper set(String fieldName, Object value) {
    return (DistributionItemWrapper) super.set(fieldName, value);
  }

  @Override
  public DistributionItemWrapper clone() {
    return (DistributionItemWrapper) super.clone();
  }

}
