/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-30 at 18:39:05 UTC 
 * Modify at your own risk.
 */

package com.appspot.rvaserver2.rise.model;

/**
 * Model definition for NewAccountResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Rise Core API (for internal use only). For a detailed
 * explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class NewAccountResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CompanyWrapper company;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private UserWrapper user;

  /**
   * @return value or {@code null} for none
   */
  public CompanyWrapper getCompany() {
    return company;
  }

  /**
   * @param company company or {@code null} for none
   */
  public NewAccountResponse setCompany(CompanyWrapper company) {
    this.company = company;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public UserWrapper getUser() {
    return user;
  }

  /**
   * @param user user or {@code null} for none
   */
  public NewAccountResponse setUser(UserWrapper user) {
    this.user = user;
    return this;
  }

  @Override
  public NewAccountResponse set(String fieldName, Object value) {
    return (NewAccountResponse) super.set(fieldName, value);
  }

  @Override
  public NewAccountResponse clone() {
    return (NewAccountResponse) super.clone();
  }

}
