/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-30 at 18:39:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.rvaserver2.test;

/**
 * Service definition for Test (v0).
 *
 * <p>
 * Rise Test API (experimental)
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TestRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Test extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the Rise Test API (experimental) library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://rvaserver2.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "test/v0/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Test(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Test(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Loopback collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Test test = new Test(...);}
   *   {@code Test.Loopback.List request = test.loopback().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Loopback loopback() {
    return new Loopback();
  }

  /**
   * The "loopback" collection of methods.
   */
  public class Loopback {

    /**
     * Create a request for the method "loopback.auth".
     *
     * This request holds the parameters needed by the test server.  After setting any optional
     * parameters, call the {@link Auth#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Auth auth() throws java.io.IOException {
      Auth result = new Auth();
      initialize(result);
      return result;
    }

    public class Auth extends TestRequest<com.appspot.rvaserver2.test.model.APIResponse> {

      private static final String REST_PATH = "loopback/auth";

      /**
       * Create a request for the method "loopback.auth".
       *
       * This request holds the parameters needed by the the test server.  After setting any optional
       * parameters, call the {@link Auth#execute()} method to invoke the remote operation. <p> {@link
       * Auth#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Auth() {
        super(Test.this, "GET", REST_PATH, null, com.appspot.rvaserver2.test.model.APIResponse.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Auth setAlt(java.lang.String alt) {
        return (Auth) super.setAlt(alt);
      }

      @Override
      public Auth setFields(java.lang.String fields) {
        return (Auth) super.setFields(fields);
      }

      @Override
      public Auth setKey(java.lang.String key) {
        return (Auth) super.setKey(key);
      }

      @Override
      public Auth setOauthToken(java.lang.String oauthToken) {
        return (Auth) super.setOauthToken(oauthToken);
      }

      @Override
      public Auth setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Auth) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Auth setQuotaUser(java.lang.String quotaUser) {
        return (Auth) super.setQuotaUser(quotaUser);
      }

      @Override
      public Auth setUserIp(java.lang.String userIp) {
        return (Auth) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String value;

      /**
     [ default: test]
     [

       */
      public java.lang.String getValue() {
        return value;
      }

      public Auth setValue(java.lang.String value) {
        this.value = value;
        return this;
      }

      @Override
      public Auth set(String parameterName, Object value) {
        return (Auth) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "loopback.noauth".
     *
     * This request holds the parameters needed by the test server.  After setting any optional
     * parameters, call the {@link Noauth#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Noauth noauth() throws java.io.IOException {
      Noauth result = new Noauth();
      initialize(result);
      return result;
    }

    public class Noauth extends TestRequest<com.appspot.rvaserver2.test.model.APIResponse> {

      private static final String REST_PATH = "loopback/noauth";

      /**
       * Create a request for the method "loopback.noauth".
       *
       * This request holds the parameters needed by the the test server.  After setting any optional
       * parameters, call the {@link Noauth#execute()} method to invoke the remote operation. <p> {@link
       * Noauth#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Noauth() {
        super(Test.this, "GET", REST_PATH, null, com.appspot.rvaserver2.test.model.APIResponse.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Noauth setAlt(java.lang.String alt) {
        return (Noauth) super.setAlt(alt);
      }

      @Override
      public Noauth setFields(java.lang.String fields) {
        return (Noauth) super.setFields(fields);
      }

      @Override
      public Noauth setKey(java.lang.String key) {
        return (Noauth) super.setKey(key);
      }

      @Override
      public Noauth setOauthToken(java.lang.String oauthToken) {
        return (Noauth) super.setOauthToken(oauthToken);
      }

      @Override
      public Noauth setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Noauth) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Noauth setQuotaUser(java.lang.String quotaUser) {
        return (Noauth) super.setQuotaUser(quotaUser);
      }

      @Override
      public Noauth setUserIp(java.lang.String userIp) {
        return (Noauth) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String value;

      /**
     [ default: test]
     [

       */
      public java.lang.String getValue() {
        return value;
      }

      public Noauth setValue(java.lang.String value) {
        this.value = value;
        return this;
      }

      @Override
      public Noauth set(String parameterName, Object value) {
        return (Noauth) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "now".
   *
   * This request holds the parameters needed by the test server.  After setting any optional
   * parameters, call the {@link Now#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Now now() throws java.io.IOException {
    Now result = new Now();
    initialize(result);
    return result;
  }

  public class Now extends TestRequest<com.appspot.rvaserver2.test.model.APIResponse> {

    private static final String REST_PATH = "now";

    /**
     * Create a request for the method "now".
     *
     * This request holds the parameters needed by the the test server.  After setting any optional
     * parameters, call the {@link Now#execute()} method to invoke the remote operation. <p> {@link
     * Now#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Now() {
      super(Test.this, "GET", REST_PATH, null, com.appspot.rvaserver2.test.model.APIResponse.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Now setAlt(java.lang.String alt) {
      return (Now) super.setAlt(alt);
    }

    @Override
    public Now setFields(java.lang.String fields) {
      return (Now) super.setFields(fields);
    }

    @Override
    public Now setKey(java.lang.String key) {
      return (Now) super.setKey(key);
    }

    @Override
    public Now setOauthToken(java.lang.String oauthToken) {
      return (Now) super.setOauthToken(oauthToken);
    }

    @Override
    public Now setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Now) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Now setQuotaUser(java.lang.String quotaUser) {
      return (Now) super.setQuotaUser(quotaUser);
    }

    @Override
    public Now setUserIp(java.lang.String userIp) {
      return (Now) super.setUserIp(userIp);
    }

    @Override
    public Now set(String parameterName, Object value) {
      return (Now) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "whoami".
   *
   * This request holds the parameters needed by the test server.  After setting any optional
   * parameters, call the {@link Whoami#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Whoami whoami() throws java.io.IOException {
    Whoami result = new Whoami();
    initialize(result);
    return result;
  }

  public class Whoami extends TestRequest<com.appspot.rvaserver2.test.model.APIResponse> {

    private static final String REST_PATH = "whoami";

    /**
     * Create a request for the method "whoami".
     *
     * This request holds the parameters needed by the the test server.  After setting any optional
     * parameters, call the {@link Whoami#execute()} method to invoke the remote operation. <p> {@link
     * Whoami#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Whoami() {
      super(Test.this, "GET", REST_PATH, null, com.appspot.rvaserver2.test.model.APIResponse.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Whoami setAlt(java.lang.String alt) {
      return (Whoami) super.setAlt(alt);
    }

    @Override
    public Whoami setFields(java.lang.String fields) {
      return (Whoami) super.setFields(fields);
    }

    @Override
    public Whoami setKey(java.lang.String key) {
      return (Whoami) super.setKey(key);
    }

    @Override
    public Whoami setOauthToken(java.lang.String oauthToken) {
      return (Whoami) super.setOauthToken(oauthToken);
    }

    @Override
    public Whoami setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Whoami) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Whoami setQuotaUser(java.lang.String quotaUser) {
      return (Whoami) super.setQuotaUser(quotaUser);
    }

    @Override
    public Whoami setUserIp(java.lang.String userIp) {
      return (Whoami) super.setUserIp(userIp);
    }

    @Override
    public Whoami set(String parameterName, Object value) {
      return (Whoami) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Test}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Test}. */
    @Override
    public Test build() {
      return new Test(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TestRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTestRequestInitializer(
        TestRequestInitializer testRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(testRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
